import {createRequire} from 'node:module';
import {mkdirSync,writeFileSync} from 'node:fs';
const {chromium,expect:baseExpect}=createRequire('/home/ubuntu/repos/MapleStory2-Handbook/package.json')('@playwright/test');
const expect=baseExpect.configure({timeout:90000});
const browser=await chromium.launch({executablePath:'/home/ubuntu/.cache/ms-playwright/chromium-1243/chrome-linux-arm64/chrome',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1100}});page.setDefaultTimeout(90000);
const dir=process.env.MOVEMENT_EVIDENCE??'NifToGltf/obj/outfit-studio-20260908/movement';mkdirSync(dir,{recursive:true});
const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
const ready=()=>expect(page.getByRole('button',{name:'Save image',exact:true})).toBeEnabled();
const slot=name=>page.getByRole('button',{name:new RegExp('^'+name+':')});
const state=()=>page.locator('[aria-label="Outfit preview"]');
async function check(name,result){expect(result,name).toBeTruthy();checks.push(name);console.log('PASS',name);}
async function equip(name,id){await slot(name).click();await page.getByRole('searchbox',{name:'Find an item',exact:true}).fill(String(id));await page.getByRole('button',{name:/^Equip /}).first().click();await ready();}
async function openControls(){if(!await page.locator('.customize').evaluate(el=>el.open))await page.locator('.customize summary').click();}
async function shaderCurrent(){return state().evaluate(el=>{const v=el.outfitViewer;v.renderer.render(v.scene,v.camera);let count=0,valid=true;v.scene.traverse(n=>{if(n.isMesh)for(const m of Array.isArray(n.material)?n.material:[n.material]){const u=v.renderer.properties.get(m).uniforms;if(u?.faceDecal){count++;valid&&=u.faceDecal.value===v.decal.texture&&JSON.stringify(u.faceDecalTransform.value.toArray())===JSON.stringify(v.makeupControls.value);}}});return count>0&&valid;});}
try{
await page.goto('http://100.118.72.53:4000/outfits');await ready();
for(const id of [10400011,10400012,10400011]){await equip('Makeup',id);await check('makeup '+id+' replacement binds the current texture and transform',await shaderCurrent());}
await openControls();await page.getByRole('button',{name:'Makeup preset 2',exact:true}).click();await check('preset buttons move makeup and update the shader',await shaderCurrent()&&await state().evaluate(el=>el.outfitViewer.makeupControls.value[0]===el.outfitViewer.makeupControls.placements[1][0]));
await page.getByRole('button',{name:'Move on face',exact:true}).click();const surface=page.getByRole('button',{name:'Move makeup on face',exact:true});await surface.scrollIntoViewIfNeeded();
const points=await state().evaluate(el=>{const v=el.outfitViewer,r=el.getBoundingClientRect();for(let y=r.top+r.height*.2;y<r.top+r.height*.6;y+=8)for(let x=r.left+r.width*.35;x<r.left+r.width*.6;x+=8){const a=v.makeupPoint(x,y),b=v.makeupPoint(x+12,y+6);if(a&&b)return {x,y};}return null;});expect(points).toBeTruthy();
const before=await state().evaluate(el=>el.outfitViewer.makeupControls.value);
await page.mouse.move(points.x,points.y);await page.mouse.down();await page.mouse.move(points.x+12,points.y+6,{steps:5});await page.mouse.up();
await check('dragging the face moves the actual makeup transform',JSON.stringify(before)!==JSON.stringify(await state().evaluate(el=>el.outfitViewer.makeupControls.value))&&await shaderCurrent());
await surface.focus();const prior=await state().evaluate(el=>el.outfitViewer.makeupControls.value[0]);await surface.press('ArrowRight');await check('keyboard fine adjustment moves makeup',await state().evaluate(el=>el.outfitViewer.makeupControls.value[0])>prior);
await page.getByRole('button',{name:'Done moving',exact:true}).click();await page.getByLabel('Makeup rotation',{exact:true}).fill('30');await page.getByLabel('Makeup size',{exact:true}).fill('0.14');await check('rotation and size reach the active shader',await shaderCurrent()&&await state().evaluate(el=>Math.abs(el.outfitViewer.makeupControls.value[2]-Math.PI/6)<1e-9&&el.outfitViewer.makeupControls.value[3]===.14));
await page.locator('.fitting-room').screenshot({path:dir+'/makeup-moved.png'});
await equip('Hair',10200010);await page.getByRole('button',{name:'Move attachment 1',exact:true}).click();const hairSurface=page.getByRole('button',{name:'Move hair attachment 1',exact:true});await hairSurface.scrollIntoViewIfNeeded();const rect=await hairSurface.boundingBox();const tails=await state().evaluate(el=>el.outfitViewer.savedHairState.tails);
await page.mouse.move(rect.x+rect.width*.4,rect.y+rect.height*.65);await page.mouse.down();await page.mouse.move(rect.x+rect.width*.4-60,rect.y+rect.height*.65,{steps:5});await page.mouse.up();
console.log('HAIR DRAG', JSON.stringify({before: tails, after: await state().evaluate(el=>el.outfitViewer.savedHairState.tails)}));
await check('dragging hair interpolates one attachment independently',await state().evaluate((el,old)=>Math.abs(el.outfitViewer.savedHairState.tails[0].position-(old[0].position-.5))<1e-6&&JSON.stringify(el.outfitViewer.savedHairState.tails[1])===JSON.stringify(old[1]),tails));
await page.getByRole('button',{name:'Done moving',exact:true}).click();await page.getByLabel('Hair attachment 1 position',{exact:true}).fill('0.65');await check('hair position slider retains intermediate positions',await state().evaluate(el=>el.outfitViewer.savedHairState.tails[0].position===.65));
await page.getByRole('button',{name:'Import / export',exact:true}).click();await page.getByRole('button',{name:'Export current outfit',exact:true}).click();const code=await page.getByLabel('Outfit code',{exact:true}).inputValue();await page.locator('.studio-settings summary').click();await page.getByRole('button',{name:'Clear outfit',exact:true}).click();await ready();await page.getByRole('button',{name:'Import outfit',exact:true}).click();await ready();await expect(page.getByText('Outfit imported. All items and saved appearance settings restored.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Export current outfit',exact:true}).click();console.log('ROUNDTRIP',JSON.stringify(await page.evaluate(([a,b])=>[a,b].map(c=>JSON.parse(atob(c.slice(5).replaceAll('-','+').replaceAll('_','/')))),[code,await page.getByLabel('Outfit code',{exact:true}).inputValue()])),'shader',await shaderCurrent());
await check('custom makeup and fractional hair positions round trip exactly',await page.getByLabel('Outfit code',{exact:true}).inputValue()===code&&await shaderCurrent());
const invalid=await page.evaluate(code=>{const data=JSON.parse(atob(code.slice(5).replaceAll('-','+').replaceAll('_','/')));data.items.find(i=>i.makeup).makeup.offset=[.7,0];return 'MS2O.'+btoa(JSON.stringify(data)).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'');},code);await page.getByLabel('Outfit code',{exact:true}).fill(invalid);await page.getByRole('button',{name:'Import outfit',exact:true}).click();await expect(page.getByText(/Invalid outfit code, unsupported version/)).toBeVisible();await page.getByRole('button',{name:'Export current outfit',exact:true}).click();await check('invalid movement import preserves the existing outfit',await page.getByLabel('Outfit code',{exact:true}).inputValue()===code);
await page.getByRole('button',{name:'Close sharing',exact:true}).click();await page.locator('.page-header').scrollIntoViewIfNeeded();await page.screenshot({path:dir+'/desktop.png'});
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Unequip Makeup',exact:true}).click();await ready();await check('mobile slot remove clears makeup',await slot('Makeup').getAttribute('aria-label')==='Makeup: Empty'&&await state().evaluate(el=>!el.outfitViewer.makeupControls));
await page.getByRole('button',{name:'Unequip Hair',exact:true}).click();await ready();await check('mobile slot remove clears hair without horizontal overflow',await slot('Hair').getAttribute('aria-label')==='Hair: Empty'&&await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await equip('Makeup',10400011);await page.getByRole('button',{name:'Move on face',exact:true}).click();await page.getByRole('button',{name:'Move makeup on face',exact:true}).scrollIntoViewIfNeeded();
const touchPoint=await state().evaluate(el=>{const v=el.outfitViewer,r=el.getBoundingClientRect();for(let y=r.top+r.height*.2;y<r.top+r.height*.6;y+=8)for(let x=r.left+r.width*.35;x<r.left+r.width*.6;x+=8)if(v.makeupPoint(x,y)&&v.makeupPoint(x+12,y+6))return {x,y};return null;});expect(touchPoint).toBeTruthy();
const oldTouch=await state().evaluate(el=>el.outfitViewer.makeupControls.value);const cdp=await page.context().newCDPSession(page);
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:touchPoint.x,y:touchPoint.y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:touchPoint.x+12,y:touchPoint.y+6}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();
await check('touch dragging moves makeup on mobile',JSON.stringify(oldTouch)!==JSON.stringify(await state().evaluate(el=>el.outfitViewer.makeupControls.value))&&await shaderCurrent());
await page.getByRole('button',{name:'Done moving',exact:true}).click();
await equip('Makeup',10400108);await check('fixed makeup does not offer movement or rotation',await page.getByRole('button',{name:'Move on face',exact:true}).count()===0&&await state().evaluate(el=>!el.outfitViewer.makeupControls.movable&&!el.outfitViewer.makeupControls.rotatable));
await page.locator('.fitting-room').screenshot({path:dir+'/mobile.png'});await check('no browser errors',errors.length===0);
}catch(error){errors.push(error.stack??String(error));process.exitCode=1;await page.screenshot({path:dir+'/failure.png',timeout:10000}).catch(()=>{});}finally{writeFileSync(dir+'/report.json',JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks:checks.length,errors},null,2));await browser.close();}
