DROP TABLE IF EXISTS {databaseName}.maps;

create table {databaseName}.maps (
  id int not null,
  name varchar(100) not null,
  visit_count int not null default 0,
  minimap varchar(200) not null default '',
  icon varchar(200) not null default '',
  bg varchar(200) not null default '',
  description text,
  xblock_name varchar(100),
  recommended_level int default 0,
  drop_rank int default 0,
  max_capacity int default 0,
  death_penalty tinyint default 0,
  flight_enabled tinyint default 1,
  climb_enabled tinyint default 1,
  home_returnable tinyint default 1,
  is_tutorial_map tinyint default 0,
  revival_return_map_id int default 0,
  enter_return_map_id int default 0,
  minimap_width int default 0,
  minimap_height int default 0,
  bounding_box_min_x int default 0,
  bounding_box_min_y int default 0,
  bounding_box_min_z int default 0,
  bounding_box_max_x int default 0,
  bounding_box_max_y int default 0,
  bounding_box_max_z int default 0,
  block_metadata json,
  constraint maps_pk primary key (id)
) engine = InnoDB default charset = utf8mb4 collate = utf8mb4_0900_ai_ci;